package com.sinosoft.ops.cimp.entity.archive;


import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchiveMaterial generated by hbm2java
 */
@Entity
@Table(name = "ARCHIVE_MATERIAL")
public class ArchiveMaterial implements java.io.Serializable {


  private static final long serialVersionUID = -3397110084701355830L;
  private String id;
  private String empId;
  private String archiveId;
  private String categoryId;
  private String title;
  private short pageCount;
  private Date createDate;
  private String remarks;
  private int seqNum;
  private Timestamp createdStamp;
  private Timestamp createdTxStamp;
  private Timestamp lastUpdatedStamp;
  private Timestamp lastUpdatedTxStamp;

  public ArchiveMaterial() {}


  public ArchiveMaterial(String id, String empId, String archiveId, String categoryId, String title,
      short pageCount, Date createDate, int seqNum) {
    this.id = id;
    this.empId = empId;
    this.archiveId = archiveId;
    this.categoryId = categoryId;
    this.title = title ==null ? "无名称" : title;
    this.pageCount = pageCount;
    this.createDate = createDate;
    this.seqNum = seqNum;
  }

  public ArchiveMaterial(String id, String empId, String archiveId, String categoryId, String title,
      short pageCount, Date createDate, String remarks, Timestamp createdStamp,
      Timestamp createdTxStamp, Timestamp lastUpdatedStamp, Timestamp lastUpdatedTxStamp) {
    this.id = id;
    this.empId = empId;
    this.archiveId = archiveId;
    this.categoryId = categoryId;
    this.title = title;
    this.pageCount = pageCount;
    this.createDate = createDate;
    this.remarks = remarks;
    this.createdStamp = createdStamp;
    this.createdTxStamp = createdTxStamp;
    this.lastUpdatedStamp = lastUpdatedStamp;
    this.lastUpdatedTxStamp = lastUpdatedTxStamp;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false, length = 50)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Column(name = "EMP_ID", nullable = false, length = 50)
  public String getEmpId() {
    return this.empId;
  }

  public void setEmpId(String empId) {
    this.empId = empId;
  }


  @Column(name = "ARCHIVE_ID", nullable = false, length = 100)
  public String getArchiveId() {
    return this.archiveId;
  }

  public void setArchiveId(String archiveId) {
    this.archiveId = archiveId;
  }


  @Column(name = "CATEGORY_ID", nullable = false, length = 10)
  public String getCategoryId() {
    return this.categoryId;
  }

  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }


  @Column(name = "TITLE", nullable = false, length = 200)
  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Column(name = "PAGE_COUNT", nullable = false, precision = 4, scale = 0)
  public short getPageCount() {
    return this.pageCount;
  }

  public void setPageCount(short pageCount) {
    this.pageCount = pageCount;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "CREATE_DATE", nullable = false, length = 7)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "REMARKS", length = 500)
  public String getRemarks() {
    return this.remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }


  @Column(name = "CREATED_STAMP")
  public Timestamp getCreatedStamp() {
    return this.createdStamp;
  }

  public void setCreatedStamp(Timestamp createdStamp) {
    this.createdStamp = createdStamp;
  }


  @Column(name = "CREATED_TX_STAMP")
  public Timestamp getCreatedTxStamp() {
    return this.createdTxStamp;
  }

  public void setCreatedTxStamp(Timestamp createdTxStamp) {
    this.createdTxStamp = createdTxStamp;
  }


  @Column(name = "LAST_UPDATED_STAMP")
  public Timestamp getLastUpdatedStamp() {
    return this.lastUpdatedStamp;
  }

  public void setLastUpdatedStamp(Timestamp lastUpdatedStamp) {
    this.lastUpdatedStamp = lastUpdatedStamp;
  }


  @Column(name = "LAST_UPDATED_TX_STAMP")
  public Timestamp getLastUpdatedTxStamp() {
    return this.lastUpdatedTxStamp;
  }

  public void setLastUpdatedTxStamp(Timestamp lastUpdatedTxStamp) {
    this.lastUpdatedTxStamp = lastUpdatedTxStamp;
  }

  @Column(name = "SEQ_NUM")
  public int getSeqNum() {
    return seqNum;
  }


  public void setSeqNum(int seqNum) {
    this.seqNum = seqNum;
  }



}


